[project]
name = "inventory-stock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "streamlit>=1.52.0",
    "streamlit-autorefresh>=1.0.1",
]
